apiVersion: v1
kind: Secret
metadata:
  name: mcp-server-secrets
  namespace: mcp-server
type: Opaque
stringData:
  AUTH_AUDIENCE: "REPLACE_ME"
  AUTH_TENANT_ID: "REPLACE_ME"
  AUTH_REQUIRED_ROLES: "REPLACE_ME"
  AUTH_ACCEPT_SCOPES: "REPLACE_ME"
  ALLOWED_ORIGINS: "REPLACE_ME"
